export const LIST_DATA_PRODUK = "LIST_DATA_PRODUK";
export const IS_LOADING_LIST_PRODUK = "IS_LOADING_LIST_PRODUK";
export const ID_PENJUAL_FILTER_PRODUK = "ID_PENJUAL_FILTER_PRODUK";
export const NAMA_BARANG_FILTER_PRODUK = "NAMA_BARANG_FILTER_PRODUK";
export const ERROR_PRODUK = "ERROR_PRODUK";
