export const INPUT_NAMA_PENJUAL = "INPUT_NAMA_PENJUAL";
export const INPUT_KOTA_PENJUAL = "INPUT_KOTA_PENJUAL";
export const ERROR_INPUT_TAMBAH_PENJUAL = "ERROR_INPUT_TAMBAH_PENJUAL";
export const IS_DISABLED_BUTTON_TAMBAH_PENJUAL =
  "IS_DISABLED_BUTTON_TAMBAH_PENJUAL";
