export const ID_PENJUAL_TAMBAH_PRODUK = "ID_PENJUAL_TAMBAH_PRODUK";
export const NAMA_BARANG_TAMBAH_PRODUK = "NAMA_BARANG_TAMBAH_PRODUK";
export const SATUAN_TAMBAH_PRODUK = "SATUAN_TAMBAH_PRODUK";
export const HARGA_SATUAN_TAMBAH_PRODUK = "HARGA_SATUAN_TAMBAH_PRODUK";
export const DESKRIPSI_TAMBAH_PRODUK = "DESKRIPSI_TAMBAH_PRODUK";
export const ERROR_INPUT_TAMBAH_PRODUK = "ERROR_INPUT_TAMBAH_PRODUK";
export const IS_DISABLED_BUTTON_TAMBAH_PRODUK =
  "IS_DISABLED_BUTTON_TAMBAH_PRODUK";
